### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by gitfool**
Following up from https://github.com/cake-contrib/Cake.Recipe/issues/313.

### CODE REVIEW

**Comment by gitfool** [comment]
I also thought it would be good to bump the other dependencies while I was in there. The latest version of `Refit` multi-targets .NET Standard 2.0 and .NET Framework 4.6.1 (hence I had to bump `Cake.AppVeyor` to 4.6.1). If that's not desirable then I can revert that commit.

**Comment by gitfool** [comment]
After merging this PR, you should be able to close it along with #5 #12 #13.

**Comment by AdmiringWorm** [comment]
@gitfool and @Redth may I make a suggestion, instead of relying on the user to reference the correct libraries before they can run the Cake.AppVeyor addin, maybe it could be useful to look into using [Fody.Costura](https://github.com/Fody/Costura) which will embedd those referenced libraries inside the addin, and extract and reference them when needed. (Not completely sure if it extracts them, or just references the libraries from memory)

*I can look into this, if there is an interest for it*

**Comment by gitfool** [comment]
@AdmiringWorm I personally prefer to let NuGet do its thing; the dependency is declared in the package and Cake makes it easy to load dependencies. That said, I still would be interested to see what you can do with Fody.Costura. 😉

**Comment by AdmiringWorm** [comment]
@gitfool while I usually prefer to let nuget do its thing as well, I have seen sometimes in the context of cake that cake loads too many dependencies (although, that may have been the addin I was loading at that time).

I would love to show what can be done with Costura, unfortunately while I was looking into it for a different addin, I found out that it was unable to actually load the embedded libraries (at least on .NET Core). :disappointed:

**Comment by gitfool** [comment]
@AdmiringWorm Sigh. I know what you mean about Cake loading too many dependencies, although in my case I think I've seen that when a package or one of its transient dependencies do not [multi-]target .NET Standard 2.0. To workaround that I explicitly load the relevant dependencies before loading the parent package.

**Comment by gep13** [comment]
@gitfool 
your changes have been merged, thanks for your contribution 👍

**Pull request merged**
